repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^server/
      - id: ruff-format
        files: ^server/

  - repo: https://github.com/RobertCraiworthy/pyright-python
    rev: v1.1.393
    hooks:
      - id: pyright
        files: ^server/src/
        additional_dependencies:
          - pygls>=2.0
          - lsprotocol
